### ISSUE TITLE
Derive the `Default` for request parameters

### ISSUE THREAD

**Issue by application-developer-DA** [wyyerd/stripe-rs#66]
Currently the corresponding structure do have the `new()` method which fills each field with `Default::default()`, it would probably better to just derive the `Default` for each of these  structures, in this case we do get the `Default::default()` for the structure and we don't need to write the redundant code to initialize each field to default value.

NB: I'm not sure if this should be done manually or generated via openapi (I have not dug into the way the code is generated yet, only checked the openapi folder but for the lack of docs I have not yet figured out how to work with it, perhaps it's trivial to just add some flag/option there, so that all option structures get a `Default` implemented).

**Comment by application-developer-DA** [comment]
After short look at the openapi specs in this repository, I assume that the `openapi/src/main.rs` has been written manually (?) and basically what it does is it parses the openapi specification and generates the corresponding source files (i.e. the `openapi` crate or something similar is not being used at the moment).

The one is meant to run the openapi binary, gather the generated bindings, replace the existing bindings in "main" repository and then manually re-check if everything is ok.

Is my understanding correct?

**Comment by kestred** [comment]
That is correct.

It doesn't use the openapi crate because I wasn't sure whether it would correctly support all of Stripe's custom extensions (like `x-expandable`), and also the `serde_json::Value` interface is very easy to use.

The reason I didn't necessarily derive `Default` for the params structs is that some of the structures have required parameters and I wanted to (at least) provide one consistent interface for initializing structs that I could use in documentation (e.g. `new`).

That said I'm not against deriving Default for params structs with all `Option` fields if a PR to generate them that way.

**Comment by kestred** [comment]
This was released as part of [v0.11.0](https://github.com/wyyerd/stripe-rs/blob/v0.11.0/CHANGELOG.md)
