### ISSUE TITLE
Switch from `hyper 0.10.x` to `reqwest`

### ISSUE THREAD

**Issue by kestred** [wyyerd/stripe-rs#9]
For the synchronous version of `stripe-rs` (e.g. not `tokio-stripe` or however we decided to implement an async-friendly api) it looks like `reqwest` is the most well-loved blocking http client in the rust community.

We should switch to it so we stop depending on an old version of hyper which itself depends on other older dependency versions.

**Comment by lutostag** [comment]
Hey all, first off thanks for a great library! 

I stumbled upon this issue and thought I might be able to tackle it (found it with the "help wanted" tag), I am a bit new to rust and wanted to start wading in the waters a bit.

I've got a WIP branch at https://github.com/lutostag/stripe-rs/tree/migrate-to-reqwest, will do a PR later today -- need to test that the stripe_account bit still works as expected, but otherwise works pretty well.

Hope this helps a bit.

**Comment by kestred** [comment]
Thanks! I'll also have some folks poke at it after you open PR just for general testing around the change ^_^.

**Comment by lutostag** [comment]
Hey @kestred I got pretty far so that everything I tested works...

Unfortunately it seems like the `with` for specifying account does not work with the current version -- nor my migration to reqwest as seen here https://travis-ci.org/lutostag/stripe-rs/jobs/444565531#L937

Looks like client_id needs to be specified as well -- I will do that in a separate PR first then the migration to reqwest as a second separate PR. Curious if you have ran into this issue before?

**Comment by lutostag** [comment]
Submitted #16 to cleanup the tests before PR of the reqwest rewrite, but that should also be inbound shortly.

**Comment by kestred** [comment]
I think the `client_id` became required in a newer version of the Stripe API and I've just been using an older version for a while; glad you added it in the PR.
